const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.Sin,
		C3.Behaviors.solid,
		C3.Plugins.Button,
		C3.Plugins.TiledBg,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Plugins.Tilemap,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Behaviors.destroy,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.video.Acts.Pause
	];
};
self.C3_JsPropNameTable = [
	{FundoSeleção: 0},
	{SeleçãoTXT: 0},
	{Sprite: 0},
	{Mouse: 0},
	{Teclado: 0},
	{Projétil: 0},
	{DisparoMagico: 0},
	{Senóide: 0},
	{Sólido: 0},
	{Slime: 0},
	{Sprite4: 0},
	{Vidas: 0},
	{Vida: 0},
	{ID: 0},
	{checkpoint: 0},
	{TextoMorte: 0},
	{BotãoRecomeçar: 0},
	{BotãoCheckpoint: 0},
	{Sprite5: 0},
	{PlanoDeFundoEmBlocos: 0},
	{Sprite6: 0},
	{MAPA2SPAWN: 0},
	{Sprite7: 0},
	{NewGame: 0},
	{FundoMenu: 0},
	{Sprite8: 0},
	{Sprite3: 0},
	{BotaoMago: 0},
	{BotãoGuerreiro: 0},
	{Fixar: 0},
	{CentrarEm: 0},
	{Maguinho: 0},
	{Plataforma: 0},
	{personagem_sensor: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{Mosaico9: 0},
	{moeda: 0},
	{spikes: 0},
	{Sprite10: 0},
	{Mosaico: 0},
	{TXTMOEDSA: 0},
	{Senóide2: 0},
	{mosca: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Mosaico2: 0},
	{Sprite2: 0},
	{btnMENUPRINCIPAL: 0},
	{btnCHECKPOINT: 0},
	{Navegador: 0},
	{AGUAMORTE: 0},
	{PlanoDeFundoEmBlocos6: 0},
	{PlanoDeFundoEmBlocos7: 0},
	{Mosaico3: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{"1PARA2": 0},
	{"2PARA3": 0},
	{COMPRAVIDA: 0},
	{life: 0},
	{Interpolação: 0},
	{BOSFinal: 0},
	{DestruirExternamente: 0},
	{AtaqueBoss: 0},
	{vidaBoss: 0},
	{Sprite13: 0},
	{Sprite9: 0},
	{Sprite14: 0},
	{"3PARA4": 0},
	{PlanoDeFundoEmBlocos8: 0},
	{Mosaico4: 0},
	{PARAFINAL: 0},
	{fundoCASTLE: 0},
	{Mosaico5: 0},
	{Mosaico6: 0},
	{Áudio: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Vídeo: 0},
	{Vídeo2: 0},
	{Texto: 0},
	{checkpointAtual: 0},
	{moedas: 0},
	{layoutMorte: 0},
	{podeatacar: 0},
	{direção: 0}
];

self.InstanceType = {
	FundoSeleção: class extends self.ISpriteInstance {},
	SeleçãoTXT: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Teclado: class extends self.IInstance {},
	DisparoMagico: class extends self.ISpriteInstance {},
	Slime: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Vida: class extends self.ISpriteInstance {},
	checkpoint: class extends self.ISpriteInstance {},
	TextoMorte: class extends self.ITextInstance {},
	BotãoRecomeçar: class extends self.IButtonInstance {},
	BotãoCheckpoint: class extends self.IButtonInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	MAPA2SPAWN: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	NewGame: class extends self.ISpriteInstance {},
	FundoMenu: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	BotaoMago: class extends self.ISpriteInstance {},
	BotãoGuerreiro: class extends self.ISpriteInstance {},
	Maguinho: class extends self.ISpriteInstance {},
	personagem_sensor: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	Mosaico9: class extends self.ITilemapInstance {},
	moeda: class extends self.ISpriteInstance {},
	spikes: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Mosaico: class extends self.ITilemapInstance {},
	TXTMOEDSA: class extends self.ITextInstance {},
	mosca: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	Mosaico2: class extends self.ITilemapInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	btnMENUPRINCIPAL: class extends self.ISpriteInstance {},
	btnCHECKPOINT: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	AGUAMORTE: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos6: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos7: class extends self.ITiledBackgroundInstance {},
	Mosaico3: class extends self.ITilemapInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	_1PARA2: class extends self.ISpriteInstance {},
	_2PARA3: class extends self.ISpriteInstance {},
	COMPRAVIDA: class extends self.IButtonInstance {},
	BOSFinal: class extends self.ISpriteInstance {},
	AtaqueBoss: class extends self.ISpriteInstance {},
	vidaBoss: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	_3PARA4: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos8: class extends self.ITiledBackgroundInstance {},
	Mosaico4: class extends self.ITilemapInstance {},
	PARAFINAL: class extends self.ISpriteInstance {},
	fundoCASTLE: class extends self.ITilemapInstance {},
	Mosaico5: class extends self.ITilemapInstance {},
	Mosaico6: class extends self.ITilemapInstance {},
	Áudio: class extends self.IInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Vídeo: class extends self.IWorldInstance {},
	Vídeo2: class extends self.IWorldInstance {},
	Texto: class extends self.ITextInstance {}
}